#!/usr/bin/env bash
set -euo pipefail

# Seed sample data into be-blog via REST APIs.
# Usage:
#   bash scripts/seed_be_blog.sh
#   BASE_URL=http://localhost:8080 bash scripts/seed_be_blog.sh

BASE_URL="${BASE_URL:-http://localhost:8080}"
# Posts and catalog mutations require ROLE_ADMIN (see SecurityConfig).
USERNAME="${SEED_USERNAME:-admin@123}"
EMAIL="${SEED_EMAIL:-admin@example.com}"
PASSWORD="${SEED_PASSWORD:-admin123}"

BOOK_COUNT="${BOOK_COUNT:-5}"
POST_COUNT="${POST_COUNT:-5}"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

echo "==> BASE_URL: $BASE_URL"
echo "==> User: $USERNAME / $EMAIL"

json_value() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
import json,sys
path,key=sys.argv[1],sys.argv[2]
try:
    data=json.load(open(path))
except Exception:
    print("")
    raise SystemExit(0)
v=data.get(key, "")
print("" if v is None else v)
PY
}

http_post_json() {
  local url="$1"
  local body="$2"
  local out="$3"
  local code
  code="$(curl -sS -o "$out" -w "%{http_code}" \
    -H "Content-Type: application/json" \
    -X POST "$url" \
    -d "$body")"
  echo "$code"
}

http_post_json_auth() {
  local url="$1"
  local token="$2"
  local body="$3"
  local out="$4"
  local code
  code="$(curl -sS -o "$out" -w "%{http_code}" \
    -H "Authorization: Bearer $token" \
    -H "Content-Type: application/json" \
    -X POST "$url" \
    -d "$body")"
  echo "$code"
}

http_post_multipart_auth() {
  local url="$1"
  local token="$2"
  local title="$3"
  local content="$4"
  local out="$5"
  local code
  code="$(curl -sS -o "$out" -w "%{http_code}" \
    -H "Authorization: Bearer $token" \
    -X POST "$url" \
    -F "title=$title" \
    -F "content=$content")"
  echo "$code"
}

register_file="$tmp_dir/register.json"
register_code="$(http_post_json \
  "$BASE_URL/api/auth/register" \
  "{\"username\":\"$USERNAME\",\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
  "$register_file")"

if [[ "$register_code" == "201" || "$register_code" == "200" || "$register_code" == "400" ]]; then
  echo "==> Register status: $register_code (200/201 ok, 400 usually user exists)"
else
  echo "Register failed with status $register_code"
  cat "$register_file"
  exit 1
fi

login_file="$tmp_dir/login.json"
login_code="$(http_post_json \
  "$BASE_URL/api/auth/login" \
  "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}" \
  "$login_file")"

if [[ "$login_code" != "200" ]]; then
  echo "Login failed with status $login_code"
  cat "$login_file"
  exit 1
fi

token="$(json_value "$login_file" "accessToken")"
if [[ -z "$token" ]]; then
  echo "Login response missing accessToken"
  cat "$login_file"
  exit 1
fi
echo "==> Login OK"

book_ids=()
for i in $(seq 1 "$BOOK_COUNT"); do
  out="$tmp_dir/book_$i.json"
  body="$(cat <<EOF
{"title":"Seed Book $i","isbn":"97800000000$i","description":"Seeded test book $i","language":"en","pageCount":$((200 + i))}
EOF
)"
  code="$(http_post_json_auth "$BASE_URL/api/books" "$token" "$body" "$out")"
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    bid="$(json_value "$out" "id")"
    if [[ -n "$bid" ]]; then
      book_ids+=("$bid")
      echo "==> Book $i created: $bid"
    else
      echo "Book $i created but no id in response"
      cat "$out"
    fi
  else
    echo "Book $i create failed: HTTP $code"
    cat "$out"
  fi
done

if [[ "${#book_ids[@]}" -eq 0 ]]; then
  echo "No books created. Stop."
  exit 1
fi

for i in $(seq 1 "${#book_ids[@]}"); do
  bid="${book_ids[$((i-1))]}"
  out="$tmp_dir/review_$i.json"
  body="$(cat <<EOF
{"bookId":"$bid","title":"Seed Review $i","content":"This is seeded review content for book $i.","rating":$(((i % 5) + 1)),"status":"published"}
EOF
)"
  code="$(http_post_json_auth "$BASE_URL/api/reviews" "$token" "$body" "$out")"
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    rid="$(json_value "$out" "id")"
    echo "==> Review $i created: ${rid:-<no-id>}"
  else
    echo "Review $i create failed: HTTP $code"
    cat "$out"
  fi
done

for i in $(seq 1 "$POST_COUNT"); do
  out="$tmp_dir/post_$i.json"
  code="$(http_post_multipart_auth \
    "$BASE_URL/api/posts" \
    "$token" \
    "Seed Post $i" \
    "Seeded content for post $i. Generated by script." \
    "$out")"
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    pid="$(json_value "$out" "id")"
    echo "==> Post $i created: ${pid:-<no-id>}"
  else
    echo "Post $i create failed: HTTP $code"
    cat "$out"
  fi
done

for i in $(seq 1 3); do
  out="$tmp_dir/tag_$i.json"
  code="$(http_post_json_auth \
    "$BASE_URL/api/tags" \
    "$token" \
    "{\"name\":\"seed-tag-$i\",\"slug\":\"seed-tag-$i\",\"color\":\"#22AA66\"}" \
    "$out")"
  echo "==> Tag $i status: $code"
done

for i in $(seq 1 3); do
  out="$tmp_dir/genre_$i.json"
  code="$(http_post_json_auth \
    "$BASE_URL/api/genres" \
    "$token" \
    "{\"name\":\"Seed Genre $i\",\"slug\":\"seed-genre-$i\"}" \
    "$out")"
  echo "==> Genre $i status: $code"
done

for i in $(seq 1 3); do
  out="$tmp_dir/author_$i.json"
  code="$(http_post_json_auth \
    "$BASE_URL/api/authors" \
    "$token" \
    "{\"name\":\"Seed Author $i\",\"slug\":\"seed-author-$i\",\"bio\":\"Seeded author\",\"photoUrl\":\"\"}" \
    "$out")"
  echo "==> Author $i status: $code"
done

echo
echo "Done."
echo "Quick checks:"
echo "  curl \"$BASE_URL/api/posts\""
echo "  curl \"$BASE_URL/api/reviews\""
echo "  curl \"$BASE_URL/api/books\""
